# Generated by Django 5.0 on 2025-06-14 04:43

from django.db import migrations

def convert_history(apps, schema_editor):
    MedicalRecord = apps.get_model('medical_records', 'MedicalRecord')
    for record in MedicalRecord.objects.all():
        if record.medical_history and isinstance(record.medical_history, str):
            # Convert text to list
            history_list = [line.strip() for line in record.medical_history.split('\n') if line.strip()]
            record.medical_history = history_list
            record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),  # Replace with your last migration
    ]

    operations = [
        migrations.RunPython(convert_history),
    ]