# Generated by Django 5.0 on 2025-06-09 01:09

import apps.medical_records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='nfc_id',
            field=models.CharField(default=apps.medical_records.models.MedicalRecord.generate_short_id, help_text='Short ID for NFC tag', max_length=6, unique=True),
        ),
    ]
