# Generated by Django 5.0 on 2025-06-09 01:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_alter_medicalrecord_nfc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='nfc_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for NFC tag', unique=True),
        ),
    ]
