# Generated by Django 5.0 on 2025-06-09 01:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_alter_medicalrecord_nfc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='blood_type',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='nfc_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
