# Generated by Django 5.0 on 2025-06-10 16:57

import apps.medical_records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_alter_medicalrecord_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='nfc_id',
            field=models.CharField(db_index=True, default=apps.medical_records.models.MedicalRecord.generate_short_id, help_text='Short ID for NFC tag', max_length=6, unique=True),
        ),
    ]
